[build]
  publish = "dist"
  command = " "  # or leave blank for static repo

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
